export const packages = [
    {
        id: "micro-boost",
        name: "Micro Boost",
        retweets: "50 RTs",
        price: "$15",
        originalPrice: "$21",
        image: "/rocket.jpg",
        features: [
            "50 Real Retweets",
            "24-48 Hour Delivery",
            "Real Active Accounts",
            "Email Support",
            "Progress Updates",
        ],
        popular: false,
    },
    {
        id: "starter-buzz",
        name: "Starter Buzz",
        retweets: "100 RTs",
        price: "$25",
        originalPrice: "$36",
        image: "/bee.jpg",
        features: [
            "100 Real Retweets",
            "24-48 Hour Delivery",
            "Verified Accounts Mix",
            "Priority Support",
            "Detailed Report",
        ],
        popular: true,
    },
    {
        id: "viral-shot",
        name: "Viral Shot",
        retweets: "250 RTs",
        price: "$60",
        originalPrice: "$86",
        image: "/viral.jpg",
        features: [
            "250 Real Retweets",
            "48-72 Hour Delivery",
            "Premium Account Network",
            "24/7 Support",
            "Analytics Dashboard",
        ],
        popular: false,
    },
];
